### ISSUE TITLE
Segmentation fault in linux (SOLVED)

### ISSUE THREAD

**Issue by keixthb** [PhantomOtter/Gell#1]
## Steps to reproduce:

```console
git clone --depth=100 https://github.com/PhantomOtter/Gell
cd Gell/
make
 ./HDS
```

## Results:

```console
./HDS
cudaLimitStackSize: 1 KB
cudaLimitPrintfFifoSize: 3584 KB
cudaLimitMallocHeapSize: 8 MB
Free Gpu Mem: 16008 MB
Total Gpu Mem: 16269 MB
CPU Mesh memory is now allocated
GPU Mesh memory is now allocated
Mesh Concentration & E,F initialized
CPU Mesh data moved to GPU
Segmentation fault (core dumped)
```

## Tested Using:

```console
nvidia-smi
Sun Mar 31 13:02:27 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla P100-PCIE-16GB           Off |   00000000:02:00.0 Off |                    0 |
| N/A   43C    P0             28W /  250W |       4MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      4207      G   /usr/libexec/Xorg                               4MiB |
+-----------------------------------------------------------------------------------------+
```

```gcc --version```

```console
gcc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```nvcc --version```

```console
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
```

```make --version```

```console
GNU Make 4.3
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by keixthb** [comment]
# SOLVED:

For linux users, you need to make sure the data in ```Gell/data/*``` is unzipped, and then change lines 38 and 39 of ```Main.cu``` from:

```c++
std::string datapath = "D:/Gell_Data/HDS/test/";
//std::string datapath = "./data/";
``` 

to:

```c++
//std::string datapath = "D:/Gell_Data/HDS/test/";
std::string datapath = "./data/";
```

Follow paraview instructions in ```Gell/Gell User Manual.pdf```:

<img width="491" alt="Screenshot 2024-03-31 at 5 39 41 PM" src="https://github.com/PhantomOtter/Gell/assets/144962336/38b37efe-009b-4b25-b0e4-392a838adddb">

**Comment by PhantomOtter** [comment]
Nice work! I'm Glad it works for you!

**Comment by keixthb** [comment]
@PhantomOtter Thanks! It's unbelievably fast compared to PhysiCell. Have you ever considered rewriting the code using [kokkos](https://github.com/kokkos/kokkos)? Gell is really good as is, but it would be nice if we could compile for more architectures like hip/ openmp/ serial.

**Comment by PhantomOtter** [comment]
Thank you for your recommendation! We actually have been doing many Python-based cross-architecture simulations, but those are not cell-based. I did a quick search, Kokkos is definitely something I would like to look into. I am interested in upgrading Gell for vascularization and including the cross-platform abilities. However, I am busy with other projects, so there will probably be no upgrade in recent months.

**Comment by keixthb** [comment]
@PhantomOtter No worries! I also found [OpenMM](https://openmm.org), [VMD](https://www.ks.uiuc.edu/Research/vmd/), and [ya||a](https://www.cell.com/cell-systems/fulltext/S2405-4712(19)30068-7?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS2405471219300687%3Fshowall%3Dtrue). OpenMM looks really interesting, but I don't like the way they're writing it with anaconda and it's kinda a pain to build. IMO, the way you're doing it with ```make``` and ```paraview``` is way better.

Ideally, keeping all your kernels in kokkos and using distributed memory parallelism with cuda aware MPI is the way to go for something like this. You could compile the kokkos serial backend and do a mpirun on your cpu cores--and still be able to compile for a single gpu if you wanted to. If you want to work more closely on this, you should shoot me an [email](keithhbova@unm.edu). I'm a MS student at the University of New Mexico, and I work with HPC clusters a lot. I'm not a biologist, but I think this code is really interesting and I'd like to help support y'all if I can!
